{"name": "test_login_func[invalid_user-invalid_pass-Epic sadface: Username and password do not match any user in this service-None]", "status": "passed", "parameters": [{"name": "username", "value": "'invalid_user'"}, {"name": "password", "value": "'invalid_pass'"}, {"name": "expected_error", "value": "'Epic sadface: Username and password do not match any user in this service'"}, {"name": "expected_url", "value": "None"}], "start": 1753136288659, "stop": 1753136290687, "uuid": "d52c4e10-6612-45e0-9eb1-bbced98a8d53", "historyId": "f0d321dfb9c613c5ede605e73bca0f63", "testCaseId": "8b2ccb9458f5546e22b00ba84e63598c", "fullName": "tests.web.test_login#test_login_func", "labels": [{"name": "parentSuite", "value": "tests.web"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Sokolovs-MacBook-Air.local"}, {"name": "thread", "value": "9714-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.web.test_login"}]}